name: Check run

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 16 * *"


jobs:
  check_run:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Clone a repo that is needed
        run: |
          cd ..
          git clone https://github.com/richelbilderbeek/nextflow_troubleshooting
          cd -

      - name: Get the latest Singularity
        run: |
          cd ../nextflow_troubleshooting
          ./scripts/upgrade_singularity.sh
          cd -

#      - uses: eWaterCycle/setup-singularity@v7
#        with:
#          singularity-version: 3.8.3

      - name: Build the Singularity containers
        run: ./create_singularity_containers.sh

      - name: Start the backend
        run: ./start_backend.sh


      - name: Start the frontend
        run: ./start_frontend.sh
